import { StyleSheet, Text, View } from 'react-native';

import { BrandMark } from '../BrandMark';
import { cardSizes, colors, fonts } from '../../design/tokens';
import { ShareCardPayload, ShareEvidenceItem } from './types';

type TagAFriendCardProps = {
  payload: ShareCardPayload;
};

export function TagAFriendCard({ payload }: TagAFriendCardProps) {
  const evidence = payload.evidence.slice(0, 3);
  const challenge = payload.challengePrompt ?? 'Who gave me the aux?';

  return (
    <View style={styles.card}>
      <View style={styles.backdropRuleOne} />
      <View style={styles.backdropRuleTwo} />

      <View style={styles.header}>
        <BrandMark size="small" light />
        <Text style={styles.caseNumber}>{payload.caseNumber}</Text>
      </View>

      <View style={styles.hookBlock}>
        <Text style={styles.kicker}>Challenge card</Text>
        <Text adjustsFontSizeToFit minimumFontScale={0.72} numberOfLines={3} style={styles.hook}>
          {challenge.toUpperCase()}
        </Text>
      </View>

      <View style={styles.verdictModule}>
        <View style={styles.scorePuck}>
          <Text style={styles.score}>{payload.auxRisk}</Text>
          <Text style={styles.scoreLabel}>Aux risk</Text>
        </View>
        <View style={styles.verdictCopy}>
          <Text style={styles.verdictLabel}>Verdict</Text>
          <Text adjustsFontSizeToFit minimumFontScale={0.72} numberOfLines={2} style={styles.verdictTitle}>
            {payload.verdictTitle}
          </Text>
          <Text numberOfLines={2} style={styles.charge}>
            {payload.charge}
          </Text>
        </View>
      </View>

      <View style={styles.friendSlots}>
        <FriendSlot index={1} label="Would defend me" />
        <FriendSlot index={2} label="Would take the aux" />
        <FriendSlot index={3} label="Would report this" />
      </View>

      <View style={styles.evidenceStrip}>
        {evidence.map((item) => (
          <ChallengeEvidence key={item.key} item={item} />
        ))}
      </View>

      <View style={styles.footer}>
        <Text style={styles.footerTitle}>Tag the friend responsible.</Text>
        <Text style={styles.footerText}>
          {payload.watermarkEnabled ? 'Generated by SongCourt' : payload.createdAt}
        </Text>
      </View>
    </View>
  );
}

function FriendSlot({ index, label }: { index: number; label: string }) {
  return (
    <View style={styles.friendSlot}>
      <View style={styles.friendIndex}>
        <Text style={styles.friendIndexText}>{index}</Text>
      </View>
      <View style={styles.friendLine} />
      <Text style={styles.friendLabel}>{label}</Text>
    </View>
  );
}

function ChallengeEvidence({ item }: { item: ShareEvidenceItem }) {
  return (
    <View style={styles.evidenceItem}>
      <Text numberOfLines={1} style={styles.evidenceValue}>
        {item.value}
      </Text>
      <Text numberOfLines={1} style={styles.evidenceLabel}>
        {item.label}
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  card: {
    width: cardSizes.story.width,
    height: cardSizes.story.height,
    backgroundColor: colors.ink,
    overflow: 'hidden',
  },
  backdropRuleOne: {
    position: 'absolute',
    left: -120,
    top: 470,
    width: 1320,
    height: 360,
    backgroundColor: colors.courtRed,
    opacity: 0.12,
    transform: [{ rotate: '-9deg' }],
  },
  backdropRuleTwo: {
    position: 'absolute',
    left: 72,
    top: 1030,
    width: 936,
    borderColor: colors.warmIvory,
    borderTopWidth: 2,
    opacity: 0.16,
  },
  header: {
    position: 'absolute',
    left: 72,
    top: 72,
    width: 936,
    height: 92,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  caseNumber: {
    color: colors.paperTan,
    fontFamily: fonts.mono,
    fontSize: 28,
    fontWeight: '900',
  },
  hookBlock: {
    position: 'absolute',
    left: 72,
    top: 230,
    width: 936,
  },
  kicker: {
    color: colors.courtRed,
    fontFamily: fonts.body,
    fontSize: 30,
    fontWeight: '900',
  },
  hook: {
    color: colors.warmIvory,
    fontFamily: fonts.body,
    fontSize: 128,
    fontWeight: '900',
    letterSpacing: -5,
    lineHeight: 132,
    marginTop: 26,
  },
  verdictModule: {
    position: 'absolute',
    left: 72,
    top: 700,
    width: 936,
    minHeight: 300,
    borderColor: colors.courtRed,
    borderRadius: 26,
    borderWidth: 4,
    flexDirection: 'row',
    padding: 30,
  },
  scorePuck: {
    width: 210,
    alignItems: 'center',
    backgroundColor: colors.warmIvory,
    borderRadius: 20,
    justifyContent: 'center',
  },
  score: {
    color: colors.ink,
    fontFamily: fonts.mono,
    fontSize: 98,
    fontWeight: '900',
    lineHeight: 106,
  },
  scoreLabel: {
    color: colors.mutedInk,
    fontFamily: fonts.body,
    fontSize: 22,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  verdictCopy: {
    flex: 1,
    justifyContent: 'center',
    paddingLeft: 34,
  },
  verdictLabel: {
    color: colors.paperTan,
    fontFamily: fonts.body,
    fontSize: 24,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  verdictTitle: {
    color: colors.courtRed,
    fontFamily: fonts.body,
    fontSize: 64,
    fontWeight: '900',
    lineHeight: 70,
    marginTop: 10,
  },
  charge: {
    color: colors.warmIvory,
    fontFamily: fonts.body,
    fontSize: 30,
    fontWeight: '700',
    lineHeight: 40,
    marginTop: 10,
  },
  friendSlots: {
    position: 'absolute',
    left: 72,
    top: 1080,
    width: 936,
    gap: 26,
  },
  friendSlot: {
    height: 126,
    alignItems: 'center',
    borderColor: '#51483F',
    borderRadius: 18,
    borderWidth: 3,
    flexDirection: 'row',
    paddingHorizontal: 28,
  },
  friendIndex: {
    width: 58,
    height: 58,
    alignItems: 'center',
    borderColor: colors.courtRed,
    borderRadius: 29,
    borderWidth: 3,
    justifyContent: 'center',
  },
  friendIndexText: {
    color: colors.warmIvory,
    fontFamily: fonts.mono,
    fontSize: 26,
    fontWeight: '900',
  },
  friendLine: {
    flex: 1,
    borderColor: '#766C5F',
    borderTopWidth: 3,
    marginHorizontal: 24,
  },
  friendLabel: {
    color: colors.paperTan,
    fontFamily: fonts.body,
    fontSize: 26,
    fontWeight: '800',
    width: 250,
  },
  evidenceStrip: {
    position: 'absolute',
    left: 72,
    top: 1510,
    width: 936,
    flexDirection: 'row',
    gap: 18,
  },
  evidenceItem: {
    flex: 1,
    height: 150,
    backgroundColor: colors.warmIvory,
    borderRadius: 18,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  evidenceValue: {
    color: colors.courtRed,
    fontFamily: fonts.mono,
    fontSize: 42,
    fontWeight: '900',
  },
  evidenceLabel: {
    color: colors.ink,
    fontFamily: fonts.body,
    fontSize: 24,
    fontWeight: '900',
    marginTop: 8,
  },
  footer: {
    position: 'absolute',
    left: 72,
    top: 1715,
    width: 936,
    minHeight: 130,
    borderColor: colors.courtRed,
    borderRadius: 22,
    borderWidth: 3,
    justifyContent: 'center',
    paddingHorizontal: 34,
  },
  footerTitle: {
    color: colors.warmIvory,
    fontFamily: fonts.body,
    fontSize: 42,
    fontWeight: '900',
  },
  footerText: {
    color: colors.paperTan,
    fontFamily: fonts.body,
    fontSize: 26,
    fontWeight: '700',
    marginTop: 8,
  },
});
